### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by slavkoja** [prehensilecode/python-daemon-example#1]
Hi, i found your post about python daemon & PID file as useful, because it is poorly documented.

Will be great, if you mention the PID file locking exception handling too. There can be raised two exceptions (both from lockfile package), the ``AlreadyLocked`` and ``LockTimeout`` and they have to be catched for situations, where two processes are trying to open the same PID file (eg. running already running daemon), eg.:
```python
import time
from daemon.pidfile import TimeoutPIDLockFile
from lockfile import AlreadyLocked, LockTimeout

pidfile = TimeoutPIDLockFile("/tmp/pydaemon.lock")
context.pidfile = pidfile

# enter daemon context
try:
    with context:
        # check daemon status
        while context.is_open:
            print ("Hello world", os.getpid())
            time.sleep(2)
except (AlreadyLocked, LockTimeout) as err:
    print(err)
```

The ``AlreadyLocked`` exception is raised if timeout is set to ``None`` (default) or ≤0, the ``LockTimeout`` happens after timeout seconds, if timeout is > 0.

**Comment by axlroden** [comment]
wouldn't you do exit(1) to indicate an exit with errors?

``` python
except (AlreadyLocked, LockTimeout) as err:
    print(err)
    exit(1)
```
