### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Franck78** [prehensilecode/python-daemon-example#3]
I tried to be 'constructive' most of the time.
But here it's simple:

-no errors
-not working

Under UBUNTU server 
 _Linux www 5.15.0-1050-kvm #55-Ubuntu SMP Wed Jan 17 14:21:23 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux_

Copy paste the code, tried 4 hours getting at least some indication but nothing after
`
with daemon.DaemonContext
`

and no this error was not blocking:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/daemon/daemon.py", line 578, in change_working_directory
    os.chdir(directory)
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/eg_daemon'

```
Run with

`sudo python3 x.py
`

**Comment by prehensilecode** [comment]
> I tried to be 'constructive' most of the time. But here it's simple:
> 
> -no errors -not working
> 
> Under UBUNTU server _Linux www 5.15.0-1050-kvm #55-Ubuntu SMP Wed Jan 17 14:21:23 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux_
> 
> Copy paste the code, tried 4 hours getting at least some indication but nothing after `with daemon.DaemonContext`
> 
> and no this error was not blocking:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/daemon/daemon.py", line 578, in change_working_directory
>     os.chdir(directory)
> FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/eg_daemon'
> ```
> 
> Run with
> 
> `sudo python3 x.py `

Read the README which says
```
eg_daemon.py -- the Python-based daemon itself; should be installed in /var/lib/eg_daemon/
```
